name: 4iren-infra

x-infra-template: &infra-template
  networks: [ team4-aiot-network ]
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  team4-nginx:
    <<: *infra-template
    image: nginx:latest
    container_name: team4-nginx
    volumes:
      - ./nginx/4iren-site.conf:/etc/nginx/conf.d/4iren-site.conf
      - ./nginx/logs:/var/log/nginx_custom

  team4-tunnel:
    <<: *infra-template
    container_name: team4-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  team4-grafana:
    <<: *infra-template
    image: grafana/grafana:latest
    container_name: team4-grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  team4-prometheus:
    <<: *infra-template
    image: prom/prometheus:latest
    container_name: team4-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  team4-filebeat:
    <<: *infra-template
    image: docker.elastic.co/beats/filebeat:8.10.2
    container_name: team4-filebeat
    user: root
    command: filebeat -e -strict.perms=false
    environment:
      - ELASTICSEARCH_ID=${ELASTICSEARCH_ID}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - ./monitoring/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  team4-zipkin:
    <<: *infra-template
    image: openzipkin/zipkin:latest
    container_name: team4-zipkin
    restart: unless-stopped

networks:
  team4-aiot-network:
    external: true

volumes:
  grafana-data:
  prometheus-data:
